In [1]:
test = "Hello World"
print(test)

Hello World


In [3]:
import numpy as np 
one_dim_array = np.array([1, 2, 3])
print(one_dim_array)

[1 2 3]


In [4]:
a=np.array([1, 2, 3])
print(a)
b= np.arange(1, 20,3)
print(b)


[1 2 3]
[ 1  4  7 10 13 16 19]


In [5]:
lin_space = np.linspace(1, 100, 5)
print(lin_space)
lin_space_int=np.linspace(1, 20, 5,dtype=int)
print(lin_space_int)
b_float= np.arange(1, 20,2,dtype=float)
print(b_float)

[  1.    25.75  50.5   75.25 100.  ]
[ 1  5 10 15 20]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [6]:
rand_arr=np.random.randint(1,10,(5,5))

In [7]:
print(rand_arr)

[[2 5 5 8 6]
 [1 2 6 4 8]
 [8 7 3 8 4]
 [2 5 2 3 1]
 [3 7 3 6 1]]


In [8]:
rand_arr2=np.random.rand(5,5)
print(rand_arr2)

[[0.93322637 0.63127771 0.97505726 0.21694409 0.77205623]
 [0.11284897 0.04252603 0.04651981 0.06679359 0.28519839]
 [0.36220728 0.92521005 0.38927917 0.16127786 0.01453752]
 [0.1661135  0.20713096 0.92687889 0.84902464 0.06057952]
 [0.38418612 0.55786382 0.37526817 0.97855141 0.45098345]]


In [9]:
rand_arr3=np.random.randint(1,10)

In [10]:
print(rand_arr3)

5


In [11]:
# Generate an array of 10 random integers between 1 and 9 (inclusive)
rand_arr3 = np.random.randint(1, 10, size=10)

# Print the array
print(rand_arr3)

[2 5 1 9 8 4 8 8 1 3]


In [12]:
one_dim_array = np.array([1, 2, 3,4,5,6,7,8,9])
multi_dim_arr=np.reshape(one_dim_array,(3,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
vector=np.array([1,2,3,4,5,6,7,8,9])

In [15]:
vector *10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
a1=np.array([[1,2],
            [3,4]])
a2=np.array([[5,6],[7,8]])
vert_stack= np.vstack((a1,a2))
print(vert_stack)
horz_stack= np.hstack((a1,a2))
print(horz_stack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
